services:
  - type: web
    name: dodo-todo-api
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: onboarding@resend.dev
      - key: OTP_EXPIRES_MINUTES
        value: "5"
